project:
  type: website
  output-dir: docs

website:
  title: "Danki Impact Scoring"
  navbar:
    left:
      - text: "Methodology"
        href: report/index.qmd
      - text: "Scoring App"
        href: report/app.qmd
    right:
      - text: "Danki Studio"
        href: "https://dankistudio.com"

format:
  html:
    theme: cosmo
    css: report/report-style.css
    toc: true